### ISSUE TITLE
Compilation issue

### ISSUE THREAD

**Issue by Shrey-25** [evmbots/mevbot#2]
Getting error message during compilation "Error: not found github.com/pancakeswap/pancake-swap-periphery/blob/master/contracts/interfaces/IPancakeRouter01.sol"

**Comment by evmbots** [comment]
@Shrey-25 
Have you selected the correct compiler version? 
Is your network able to access gitHub without any issues?

**Comment by Shrey-25** [comment]
I am using 0.6.6 compiler .I think i am not able to access github. What should I do?

**Comment by evmbots** [comment]
> I am using 0.6.6 compiler .I think i am not able to access github url. What should I do?

@Shrey-25 , use `mevbot_for_cannot_access_github_devices.sol` instead.

**Comment by Shrey-25** [comment]
@evmbots
![image](https://github.com/evmbots/mevbot/assets/66828472/49e9e1cc-c532-46ed-bc9e-6448a86731a7)

**Comment by Shrey-25** [comment]
> > I am using 0.6.6 compiler .I think i am not able to access github url. What should I do?
> 
> @Shrey-25 , use `mevbot_for_cannot_access_github_devices.sol` instead.

It worked,Thanks
